name: food_service

services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./.env.docker
        ports:
            - "8081:8081"
        # volumes:
        #     - ./.env:/.env:ro
        depends_on:
            - database

volumes:
    postgres_data:
